version: '3'
services:
    matching_host:
        volumes:
            - "./matching_host/matchingproj:/app/matchingproj"
            - "./log:/var/log"
        ports:
            - "50051:50051"