version: '3'
services:
    semibot_host:
        build: ./semibot_host
        image: semibot_host
        container_name: semibot_host
        volumes:
            -   "./log:/var/log"
        command: >
            bash -c "DJANGO_SETTINGS_MODULE=semibot.settings celery -A semibot beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --pidfile /celerybeat.pid &
            celery -A semibot worker &
            python3"
        ports:
            - "8000:8000"
        tty: true
        depends_on:
        - semibot_db
        
    semibot_db:
        build: ./semibot_db
        image: semibot_db
        container_name: semibot_db
        command:
            - --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: Endeavor
            MYSQL_ROOT_HOST: '%'
        ports:
            - "3306:3306"
        volumes:
            - "./semibot_db/init:/docker-entrypoint-initdb.d" # db初期化
            - "mysql:/var/lib/mysql" # db永続化(コンテナ再起動後もデータ保持)

    # For celery
    redis:
        image: redis:alpine
        container_name: semibot_redis

volumes:
    mysql: # db用名前付きボリューム

