# Generated by Django 3.2.12 on 2022-04-04 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_datetime', models.DateTimeField()),
                ('personal_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_personaldata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('is_dynamic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LabelSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('const_label', models.ManyToManyField(blank=True, to='matching.Label')),
            ],
        ),
        migrations.CreateModel(
            name='TaskRequestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('task', models.CharField(max_length=20)),
                ('task_datetime', models.DateTimeField()),
                ('matching_end_datetime', models.DateTimeField()),
                ('require_candidates', models.IntegerField()),
                ('max_candidates', models.IntegerField()),
                ('callback_url', models.URLField(blank=True, null=True)),
                ('join_url', models.URLField()),
                ('cancel_url', models.URLField()),
                ('request_message', models.TextField()),
                ('join_complete_message', models.TextField()),
                ('cancel_complete_message', models.TextField()),
                ('matching_complete_message', models.TextField()),
                ('rematching_duration', models.DurationField()),
                ('next_rematching', models.DateTimeField()),
                ('is_complete', models.BooleanField(default=False)),
                ('check_joined_candidates_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='check_taskrequest', to='django_celery_beat.periodictask')),
                ('decline_candidates', models.ManyToManyField(blank=True, related_name='declined_task_request', to='matching.Candidate')),
                ('end_matching_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='end_request', to='django_celery_beat.periodictask')),
                ('joined_candidates', models.ManyToManyField(blank=True, related_name='joined_task_request', to='matching.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='ThroughRequestLabelSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.labelset')),
                ('task_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.taskrequestrequest')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='taskrequestrequest',
            name='label_set',
            field=models.ManyToManyField(through='matching.ThroughRequestLabelSet', to='matching.LabelSet'),
        ),
        migrations.AddField(
            model_name='taskrequestrequest',
            name='requesting_candidates',
            field=models.ManyToManyField(blank=True, related_name='reserve_task_request', to='matching.Candidate'),
        ),
        migrations.CreateModel(
            name='LabelValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.label')),
            ],
        ),
        migrations.AddField(
            model_name='labelset',
            name='var_label',
            field=models.ManyToManyField(blank=True, to='matching.LabelValue'),
        ),
        migrations.CreateModel(
            name='JoinResponseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_at', models.DateTimeField(auto_now_add=True)),
                ('task_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.taskrequestrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FillRequireCandidateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_at', models.DateTimeField(auto_now_add=True)),
                ('task_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.taskrequestrequest')),
            ],
        ),
        migrations.CreateModel(
            name='DeclineResponseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decline_at', models.DateTimeField(auto_now_add=True)),
                ('task_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.taskrequestrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CancelResponseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_at', models.DateTimeField(auto_now_add=True)),
                ('task_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.taskrequestrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='labelvalue',
            constraint=models.UniqueConstraint(fields=('label', 'value'), name='labelvalue_unique'),
        ),
    ]
