# Generated by Django 3.2.7 on 2021-09-21 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabelSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('const_label', models.ManyToManyField(blank=True, to='matching.Label')),
            ],
        ),
        migrations.CreateModel(
            name='TaskRequestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('task', models.CharField(max_length=20)),
                ('task_datetime', models.DateTimeField()),
                ('matching_end_datetime', models.DateTimeField()),
                ('callback_url', models.URLField()),
                ('label_set', models.ManyToManyField(to='matching.LabelSet')),
            ],
        ),
        migrations.CreateModel(
            name='LabelValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.label')),
            ],
        ),
        migrations.AddField(
            model_name='labelset',
            name='var_label',
            field=models.ManyToManyField(blank=True, to='matching.LabelValue'),
        ),
        migrations.AddConstraint(
            model_name='labelvalue',
            constraint=models.UniqueConstraint(fields=('label', 'value'), name='labelvalue_unique'),
        ),
    ]
