# Generated by Django 3.2.7 on 2021-10-12 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidate',
            new_name='PersonalData',
        ),
    ]
