# Generated by Django 3.2.7 on 2021-10-12 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_rename_candidate_personaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_datetime', models.DateTimeField()),
                ('personal_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_personaldata', to='matching.personaldata')),
            ],
        ),
        migrations.AlterField(
            model_name='taskrequestrequest',
            name='joined_candidates',
            field=models.ManyToManyField(blank=True, related_name='joined_task_request', to='matching.Candidate'),
        ),
        migrations.AlterField(
            model_name='taskrequestrequest',
            name='requesting_candidates',
            field=models.ManyToManyField(blank=True, related_name='reserve_task_request', to='matching.Candidate'),
        ),
    ]
