# Generated by Django 3.2.7 on 2021-10-17 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matching', '0003_auto_20211012_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='personal_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_personaldata', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PersonalData',
        ),
    ]
