# Generated by Django 3.2.7 on 2021-10-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_auto_20211018_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrequestrequest',
            name='cancel_complete_message',
            field=models.TextField(default='temp_cancel_msg'),
            preserve_default=False,
        ),
    ]
