# Generated by Django 3.2.7 on 2021-11-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_taskrequestrequest_cancel_complete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrequestrequest',
            name='matching_complete_message',
            field=models.TextField(default='complete_msg'),
            preserve_default=False,
        ),
    ]
