# Generated by Django 3.2.7 on 2021-11-04 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('matching', '0007_taskrequestrequest_matching_complete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrequestrequest',
            name='check_joind_candidates_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='check_taskrequest', to='django_celery_beat.periodictask'),
        ),
        migrations.AddField(
            model_name='taskrequestrequest',
            name='end_matching_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='end_request', to='django_celery_beat.periodictask'),
        ),
    ]
