# Generated by Django 3.2.7 on 2021-11-04 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0008_auto_20211104_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskrequestrequest',
            old_name='check_joind_candidates_task',
            new_name='check_joined_candidates_task',
        ),
    ]
