# Generated by Django 3.2.7 on 2021-11-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0009_rename_check_joind_candidates_task_taskrequestrequest_check_joined_candidates_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrequestrequest',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
