# Generated by Django 3.2.7 on 2021-11-09 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matching', '0010_taskrequestrequest_is_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinResponseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_at', models.DateTimeField(auto_now_add=True)),
                ('task_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.taskrequestrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FillRequireCandidateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_at', models.DateTimeField(auto_now_add=True)),
                ('task_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.taskrequestrequest')),
            ],
        ),
        migrations.CreateModel(
            name='DeclineResponseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decline_at', models.DateTimeField(auto_now_add=True)),
                ('task_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.taskrequestrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
