# Generated by Django 3.2.9 on 2021-12-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0012_cancelresponsehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrequestrequest',
            name='decline_candidates',
            field=models.ManyToManyField(blank=True, related_name='declined_task_request', to='matching.Candidate'),
        ),
    ]
