# Generated by Django 3.2.7 on 2021-10-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_datetime', models.DateTimeField()),
                ('bachelor_num', models.IntegerField()),
                ('master_num', models.IntegerField()),
            ],
        ),
    ]
