# Generated by Django 3.2.7 on 2021-10-27 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_app', '0002_auto_20211020_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrequest',
            name='matching_end_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='taskrequest',
            name='bachelor_num',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='taskrequest',
            name='master_num',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
