# Generated by Django 3.2.9 on 2021-11-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_app', '0003_auto_20211027_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrequest',
            name='is_random',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
