# Generated by Django 3.2.7 on 2021-10-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='require_label',
            field=models.ManyToManyField(blank=True, related_name='require_task', to='data_manager.Label'),
        ),
        migrations.AlterField(
            model_name='taskrequest',
            name='recommend_label',
            field=models.ManyToManyField(blank=True, related_name='recommend_task', to='data_manager.Label'),
        ),
        migrations.AlterField(
            model_name='taskrequest',
            name='recommend_label_value',
            field=models.ManyToManyField(blank=True, related_name='recommend_task', to='data_manager.LabelValue'),
        ),
    ]
