# Generated by Django 3.2.6 on 2021-08-29 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='label',
            name='labelset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='data_manager.labelset'),
        ),
    ]
