# Generated by Django 3.2.7 on 2021-10-18 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0003_alter_task_require_label_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldata',
            name='message_addr',
        ),
        migrations.CreateModel(
            name='MessageAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.IntegerField(choices=[(0, 'Slack')])),
                ('userid', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_addr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
