# Generated by Django 3.2.7 on 2021-10-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0004_auto_20211018_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageaddress',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
