# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import type_pb2 as type__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='server.proto',
  package='matching',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cserver.proto\x12\x08matching\x1a\ntype.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xad\x02\n\x15\x41\x64\x64TaskRequestRequest\x12/\n\x0ctask_request\x18\x01 \x01(\x0b\x32\x19.matching.TaskRequestData\x12;\n\tlabel_set\x18\x02 \x03(\x0b\x32(.matching.AddTaskRequestRequest.LabelSet\x12\x35\n\x11matching_end_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0c\x63\x61llback_url\x18\x04 \x01(\t\x1aY\n\x08LabelSet\x12$\n\x0b\x63onst_label\x18\x01 \x03(\x0b\x32\x0f.matching.Label\x12\'\n\tvar_label\x18\x02 \x03(\x0b\x32\x14.matching.LabelValue\"\x85\x01\n\x16\x41\x64\x64TaskRequestResponse\x12\x37\n\x06result\x18\x01 \x01(\x0e\x32\'.matching.AddTaskRequestResponse.Result\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\x06Result\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x32\x65\n\x0eMatchingServer\x12S\n\x0e\x41\x64\x64TaskRequest\x12\x1f.matching.AddTaskRequestRequest\x1a .matching.AddTaskRequestResponseb\x06proto3'
  ,
  dependencies=[type__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])



_ADDTASKREQUESTRESPONSE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='matching.AddTaskRequestResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=476,
  serialized_end=509,
)
_sym_db.RegisterEnumDescriptor(_ADDTASKREQUESTRESPONSE_RESULT)


_ADDTASKREQUESTREQUEST_LABELSET = _descriptor.Descriptor(
  name='LabelSet',
  full_name='matching.AddTaskRequestRequest.LabelSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='const_label', full_name='matching.AddTaskRequestRequest.LabelSet.const_label', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='var_label', full_name='matching.AddTaskRequestRequest.LabelSet.var_label', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=373,
)

_ADDTASKREQUESTREQUEST = _descriptor.Descriptor(
  name='AddTaskRequestRequest',
  full_name='matching.AddTaskRequestRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_request', full_name='matching.AddTaskRequestRequest.task_request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='label_set', full_name='matching.AddTaskRequestRequest.label_set', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='matching_end_date', full_name='matching.AddTaskRequestRequest.matching_end_date', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='callback_url', full_name='matching.AddTaskRequestRequest.callback_url', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ADDTASKREQUESTREQUEST_LABELSET, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=373,
)


_ADDTASKREQUESTRESPONSE = _descriptor.Descriptor(
  name='AddTaskRequestResponse',
  full_name='matching.AddTaskRequestResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='matching.AddTaskRequestResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='matching.AddTaskRequestResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ADDTASKREQUESTRESPONSE_RESULT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=509,
)

_ADDTASKREQUESTREQUEST_LABELSET.fields_by_name['const_label'].message_type = type__pb2._LABEL
_ADDTASKREQUESTREQUEST_LABELSET.fields_by_name['var_label'].message_type = type__pb2._LABELVALUE
_ADDTASKREQUESTREQUEST_LABELSET.containing_type = _ADDTASKREQUESTREQUEST
_ADDTASKREQUESTREQUEST.fields_by_name['task_request'].message_type = type__pb2._TASKREQUESTDATA
_ADDTASKREQUESTREQUEST.fields_by_name['label_set'].message_type = _ADDTASKREQUESTREQUEST_LABELSET
_ADDTASKREQUESTREQUEST.fields_by_name['matching_end_date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_ADDTASKREQUESTRESPONSE.fields_by_name['result'].enum_type = _ADDTASKREQUESTRESPONSE_RESULT
_ADDTASKREQUESTRESPONSE_RESULT.containing_type = _ADDTASKREQUESTRESPONSE
DESCRIPTOR.message_types_by_name['AddTaskRequestRequest'] = _ADDTASKREQUESTREQUEST
DESCRIPTOR.message_types_by_name['AddTaskRequestResponse'] = _ADDTASKREQUESTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddTaskRequestRequest = _reflection.GeneratedProtocolMessageType('AddTaskRequestRequest', (_message.Message,), {

  'LabelSet' : _reflection.GeneratedProtocolMessageType('LabelSet', (_message.Message,), {
    'DESCRIPTOR' : _ADDTASKREQUESTREQUEST_LABELSET,
    '__module__' : 'server_pb2'
    # @@protoc_insertion_point(class_scope:matching.AddTaskRequestRequest.LabelSet)
    })
  ,
  'DESCRIPTOR' : _ADDTASKREQUESTREQUEST,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:matching.AddTaskRequestRequest)
  })
_sym_db.RegisterMessage(AddTaskRequestRequest)
_sym_db.RegisterMessage(AddTaskRequestRequest.LabelSet)

AddTaskRequestResponse = _reflection.GeneratedProtocolMessageType('AddTaskRequestResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDTASKREQUESTRESPONSE,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:matching.AddTaskRequestResponse)
  })
_sym_db.RegisterMessage(AddTaskRequestResponse)



_MATCHINGSERVER = _descriptor.ServiceDescriptor(
  name='MatchingServer',
  full_name='matching.MatchingServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=511,
  serialized_end=612,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddTaskRequest',
    full_name='matching.MatchingServer.AddTaskRequest',
    index=0,
    containing_service=None,
    input_type=_ADDTASKREQUESTREQUEST,
    output_type=_ADDTASKREQUESTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MATCHINGSERVER)

DESCRIPTOR.services_by_name['MatchingServer'] = _MATCHINGSERVER

# @@protoc_insertion_point(module_scope)
